// API route for generating PRD using Taskmaster MCP
// This will be called from the client when "Let's Build It" is clicked

import { NextRequest, NextResponse } from 'next/server'
import { writeFile, mkdir } from 'fs/promises'
import { join } from 'path'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as { 
      notes: Array<{ created_at: string; content: string; type: string }>
      subprojectId: string
      aggregatedNotes?: string
    }
    const { notes, subprojectId, aggregatedNotes } = body

    if (!notes || !Array.isArray(notes) || notes.length === 0) {
      return NextResponse.json(
        { error: 'Notes are required' },
        { status: 400 }
      )
    }

    // Format aggregated notes if not provided
    const notesContent = aggregatedNotes || notes
      .map((note, index) => {
        const timestamp = new Date(note.created_at).toISOString()
        const typeIndicator = note.type === 'image' ? '📷 Image' : '📝 Text'
        return `## Note ${index + 1} - ${typeIndicator} (${timestamp})\n\n${note.content}`
      })
      .join('\n\n---\n\n')

    // Create PRD content for Taskmaster to parse
    const prdContent = `# Subproject PRD\n\n## Notes\n\n${notesContent}\n\n## Requirements\n\n[To be generated by Taskmaster]`

    // Ensure .taskmaster/docs directory exists
    const docsDir = join(process.cwd(), '.taskmaster', 'docs')
    await mkdir(docsDir, { recursive: true })

    // Write PRD file for Taskmaster to parse
    const prdFileName = `subproject-${subprojectId}-prd.txt`
    const prdFilePath = join(docsDir, prdFileName)
    await writeFile(prdFilePath, prdContent, 'utf-8')

    // Note: Taskmaster MCP parse_prd will be called by the MCP server
    // The actual PRD generation happens via MCP, not directly here
    // For now, return the formatted notes as PRD until MCP integration is complete
    
    // TODO: Call Taskmaster MCP parse_prd tool here via MCP server
    // For now, return a formatted PRD based on notes
    const prdMarkdown = `# Product Requirements Document\n\n## Overview\n\nThis PRD is generated from ${notes.length} note(s) captured during the planning phase.\n\n## Notes Summary\n\n${notesContent}\n\n## Requirements\n\nBased on the notes above, the following requirements have been identified:\n\n- [Requirements will be generated by Taskmaster]\n\n## Next Steps\n\n- [Tasks will be generated from this PRD]`

    return NextResponse.json({
      success: true,
      prdMarkdown,
      prdFilePath,
    })
  } catch (error) {
    console.error('Error generating PRD:', error)
    return NextResponse.json(
      { error: 'Failed to generate PRD', details: String(error) },
      { status: 500 }
    )
  }
}
