// API route for generating PRD using Taskmaster
// This will be called from the client when "Let's Build It" is clicked

import { NextRequest, NextResponse } from 'next/server'
import { writeFile, mkdir } from 'fs/promises'
import { join } from 'path'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as { notes: Array<{ created_at: string; content: string }>; subprojectId: string }
    const { notes, subprojectId } = body

    if (!notes || !Array.isArray(notes) || notes.length === 0) {
      return NextResponse.json(
        { error: 'Notes are required' },
        { status: 400 }
      )
    }

    // Aggregate notes into PRD format
    const notesContent = notes
      .map((note, index) => {
        const timestamp = new Date(note.created_at).toISOString()
        return `## Note ${index + 1} (${timestamp})\n\n${note.content}`
      })
      .join('\n\n---\n\n')

    // Create a temporary PRD file for Taskmaster to parse
    const prdContent = `# Subproject PRD\n\n## Notes\n\n${notesContent}\n\n## Requirements\n\n[To be generated by Taskmaster]`

    // Ensure .taskmaster/docs directory exists
    const docsDir = join(process.cwd(), '.taskmaster', 'docs')
    await mkdir(docsDir, { recursive: true })

    // Write PRD file
    const prdFileName = `subproject-${subprojectId}-prd.txt`
    const prdFilePath = join(docsDir, prdFileName)
    await writeFile(prdFilePath, prdContent, 'utf-8')

    // TODO: Call Taskmaster MCP parse_prd tool here
    // For now, return the file path so it can be processed
    // In production, this would call the MCP tool and return the generated PRD

    return NextResponse.json({
      success: true,
      prdFilePath,
      message: 'PRD file created. Taskmaster integration pending.',
    })
  } catch (error) {
    console.error('Error generating PRD:', error)
    return NextResponse.json(
      { error: 'Failed to generate PRD', details: String(error) },
      { status: 500 }
    )
  }
}

