// API route for generating tasks from PRD using Taskmaster MCP

import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as { 
      subprojectId: string
      prdMarkdown: string
    }
    const { subprojectId, prdMarkdown } = body

    if (!prdMarkdown || prdMarkdown.trim().length === 0) {
      return NextResponse.json(
        { error: 'PRD markdown is required' },
        { status: 400 }
      )
    }

    // TODO: Call Taskmaster MCP parse_prd or expand_task tool here via MCP server
    // For now, return a formatted tasks markdown based on PRD
    
    // Generate tasks markdown from PRD
    const tasksMarkdown = `# Tasks for Subproject ${subprojectId}\n\n## Overview\n\nTasks generated from PRD:\n\n${prdMarkdown}\n\n## Task Breakdown\n\n- [Tasks will be generated by Taskmaster from the PRD above]`

    return NextResponse.json({
      success: true,
      tasksMarkdown,
    })
  } catch (error) {
    console.error('Error generating tasks:', error)
    return NextResponse.json(
      { error: 'Failed to generate tasks', details: String(error) },
      { status: 500 }
    )
  }
}

